use_frameworks!

platform :ios, '9.0'

target 'WaterFallFlowLayout_Example' do
  pod 'WaterFallFlowLayout', :path => '../'

  target 'WaterFallFlowLayout_Tests' do
    inherit! :search_paths

    
  end
end
